### PR TITLE
worked on volume button and social media icon which is in footer

### PR DESCRIPTION
**Pull request by ChetanDehane**
### 🛠️ Fixes Issue

worked on volume button. 
social media icon was not visible which is in footer now its visible.

### ✔️ Check List (Check all the applicable boxes) 

- [👍🏻  ] My code follows the code style of this project.
- [👍🏻  ] This PR does not contain plagiarized content.
- [👍🏻  ] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
Before : 

https://user-images.githubusercontent.com/62801180/156769278-3e88fea8-7830-4004-b9db-dd36ca9f01bd.mp4

after : 

https://user-images.githubusercontent.com/62801180/156769334-deb6f34e-c8b9-4f06-b855-8c58500185c4.mp4

### CODE REVIEW

**Comment by SauravMukherjee44** [comment]
@ChetanDehane Mention your issue no.

**Review by devaaquib — APPROVED** [review]

**Comment by ChetanDehane** [comment]
My issue no was #700

**Comment by devaaquib** [comment]
@ChetanDehane Your issue is closed. Don't worry XD

**Comment by ChetanDehane** [comment]
Thanks a lot.

**Pull request merged**
