### PR TITLE
Fixed the incorrect CSS for the links in Resources section

### PR DESCRIPTION
**Pull request by Ash-ishJ**
## What is the problem that is getting fixed?
Due to incorrect CSS of the links in Resources section, we can click only the text to open the link. So, I am making the whole box clickable that contains the link text.

### Before:
image

### After:
image

### CODE REVIEW

**Comment by Ash-ishJ** [comment]
@SauravMukherjee44 Please review it.

**Comment by shivam2003-dev** [comment]
Host it anywhere (e.g, replit or on other), and please comment the link so the request can be fast-forwarded. By the way Nice improvement  .

**Comment by Ash-ishJ** [comment]
Yes sure, and also I did some more changes :)
**Here is the link** - [Click here](https://angry-noether-1fee02.netlify.app/resource.html)
Please navigate to the bottom of the page and hover on **_view_** button in the study material section and see the changes.

You will observe that, 
- In original repository only the **view** text is clickable - [You can see here](https://sauravmukherjee44.github.io/Aec-Library-Website/resource.html)
- After change, whole box that contains the link is clickable
- Also, I have added hover effects to the **view** link, which you can check in the provided link.

**Comment by Ash-ishJ** [comment]
@shivam2003-dev @SauravMukherjee44 Can you please review it again?
And please provide me hacktoberfest label if possible :)

**Comment by shivam2003-dev** [comment]
Nice

**Pull request merged**
