### PR TITLE
Fixed footer section of index.html 

### PR DESCRIPTION
**Pull request by sibayanmisra2002**
### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by IAmTamal — CHANGES_REQUESTED** [review]
##  Hello there here are some things you need to do

- Mention issue number in the PR
- Add screenshots
- Add all the relevant details in the PR

**Comment by sibayanmisra2002** [comment]
SmartSelect_20221011-145710_Chrome

1. Added target = "_blank" in all resources button.
2. Fixed footer section contact, mail and LinkedIn part.
3. Provided new tab opening for terms and conditions in the company information @ footer section.

PR#1039

**Comment by sibayanmisra2002** [comment]
> ## Hello there here are some things you need to do
> * Mention issue number in the PR
> * Add screenshots
> * Add all the relevant details in the PR

Done the changes. Thank you.

**Comment by IAmTamal** [comment]
> > ## Hello there here are some things you need to do
> > 
> > * Mention issue number in the PR
> > * Add screenshots
> > * Add all the relevant details in the PR
> 
> Done the changes. Thank you.

Where is the issue number :)

**Review by SauravMukherjee44 — APPROVED** [review]

**Pull request merged**
