### PR TITLE
aligned items center in mobile view

### PR DESCRIPTION
**Pull request by codingkush**
### 🛠️ Fixes Issue
i have aligned items center in mobile view.....
now it's looking good

### 📷 Screenshots

tyu

### CODE REVIEW

**Review by devaaquib — CHANGES_REQUESTED** [review]
@codingkush Get in touch section is not responsive. take a look at it and fix the issue

**Comment by codingkush** [comment]
Ok ...

**Comment by codingkush** [comment]
will the feedback image  show in mobile view??

**Comment by codingkush** [comment]
Plz tell me...

**Comment by SauravMukherjee44** [comment]
Yes @codingkush

**Comment by codingkush** [comment]
Ok..

**Comment by codingkush** [comment]
fixed the issue and made responsive get in touch section 

screenshot :-------------

getr

**Comment by codingkush** [comment]
Is this okay???

**Pull request merged**
