### PR TITLE
Fixes issue #1212, #1270 and #1271

### PR DESCRIPTION
**Pull request by vishalsingh2972**
Hey @SauravMukherjee44 ,
This PR solves issue #1212 - I made email addresses clickable so that when you click on the email address a new email window opens with the recipient's address already filled in. The user only needs to type the body of the email. 

This PR solves issue #1270 - Corrected grammatical error in about.html

This PR solves issue #1271 - Added course image in resource.html

Issue #1212 demo after solving

https://github.com/SauravMukherjee44/Aec-Library-Website/assets/106817047/4c291c72-10ab-4314-ad98-ac6128758055

### CODE REVIEW

**Comment by vishalsingh2972** [comment]
@SauravMukherjee44 Please review my pr.

**Comment by vishalsingh2972** [comment]
@SauravMukherjee44 Please review my pr.

**Comment by vishalsingh2972** [comment]
@SauravMukherjee44 Please review my pr.

**Comment by vishalsingh2972** [comment]
@SauravMukherjee44 Please review my pr.

**Comment by vishalsingh2972** [comment]
@SauravMukherjee44 Please review my pr.

**Comment by vishalsingh2972** [comment]
@SauravMukherjee44 Please review my pr.

**Comment by vishalsingh2972** [comment]
@SauravMukherjee44 Please review my pr.

**Comment by vishalsingh2972** [comment]
@SauravMukherjee44 can you please review my pr.

**Comment by vishalsingh2972** [comment]
@SauravMukherjee44 can you please review my pr.

**Comment by rohanbabbar04** [comment]
Thanks @vishalsingh2972 Look good, 
I just made a commit to solve the merge conflicts...

**Review by rohanbabbar04 — APPROVED** [review]

**Pull request merged**
