### PR TITLE
Made some UI changes using CSS

### PR DESCRIPTION
**Pull request by Ash-ishJ**
Added some CSS and changed the font of the website to make the website look a little bit more professional.

### CODE REVIEW

**Comment by Ash-ishJ** [comment]
@SauravMukherjee44 please review the changes! 
Thanks 🙂

**Comment by SauravMukherjee44** [comment]
@Ash-ishJ Could you host your forked repository on GitHub pages and share the link or share the screenshot of changes.

**Comment by Ash-ishJ** [comment]
Yes sure. I am attaching the screenshots. And, thanks for the quick response :

- Added some paddings and removed the extra margin.
- 100% width of only book-name input was not looking good. So, made the width of all the inputs and select tags equal.
Table contents

- Changed the **Copyright**  text location to center, which was previously a little bit on left side.
Footer

**Comment by Ash-ishJ** [comment]
@SauravMukherjee44 Could you please review it again?

**Comment by SauravMukherjee44** [comment]
Hey! Add button is not working. Try to fix it and create a PR.

**Comment by Ash-ishJ** [comment]
@SauravMukherjee44 I think someone is already working on Add button.
By the way, can you please assign me with Hacktoberfest Accepted label?
Thanks :)

**Pull request merged**
