### PR TITLE
Made resources page responsive

### PR DESCRIPTION
**Pull request by gayatriagarwal19**
### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

navbar-laptop

navbar-mobile

footer-laptop

footer-mobile

### CODE REVIEW

**Comment by rohanbabbar04** [comment]
@gayatriagarwal19 You have merge conflicts, do resolve them..

**Comment by gayatriagarwal19** [comment]
@rohanbabbar04 I have resolved them, please look into it..

**Comment by rohanbabbar04** [comment]
image
In the above pic, I would want to have the search bar **horizontally centered**

**Comment by gayatriagarwal19** [comment]
I've fixed the search bar 
Resources - Google Chrome 20-06-2023 12_59_05

@rohanbabbar04 please look into it.

**Comment by rohanbabbar04** [comment]
Nice work @gayatriagarwal19

**Review by rohanbabbar04 — APPROVED** [review]

**Pull request merged**
