### PR TITLE
make a table for your books section

### PR DESCRIPTION
**Pull request by tanwi1234**
Fixed the nav alaignment issue and if any more changes is required please let me know.please review my PR #74  @SauravMukherjee44

### CODE REVIEW

**Comment by tanwi1234** [comment]
made the table for books section.please review my PR #74 @SauravMukherjee44

**Comment by SauravMukherjee44** [comment]
Could you host your repo on GitHub pages and share the link below.

**Comment by tanwi1234** [comment]
> Could you host your repo on GitHub pages and share the link below.

https://tanwi1234.github.io/Aec-Library-Website/

**Comment by SauravMukherjee44** [comment]
Hey, Everything is alright just do fetch upstream once, Update your repo and resolve conflicts.
And rename tanwi.html to index.html.

For any help, you can reach out to me : https://sauravmukherjee.bio.link/

**Comment by tanwi1234** [comment]
> Hey, @tanwi1234 Everything is alright just do fetch upstream once, Update your repo and resolve conflicts. And rename tanwi.html to index.html.
> 
> For any help, you can reach out to me: https://sauravmukherjee.bio.link/

after doing fetch upstream index file is not working. what to do now?

**Pull request closed without merging**
