### PR TITLE
Added a responsive Login Page for the students to be able to login.

### PR DESCRIPTION
**Pull request by Sampad18**
Added a responsive and interactive login page for the students to be able to login to the library website for future use.
#hacktoberfest

### CODE REVIEW

**Comment by SauravMukherjee44** [comment]
Could you host your GitHub repo on GitHub Pages and share the link below ?

**Comment by Sampad18** [comment]
Sure. Give me some time.

**Comment by Sampad18** [comment]
https://sampad18.github.io/login_page_hacktober.github.io/
The outline of the login page.

**Comment by SauravMukherjee44** [comment]
share the hosted link of this forked repository.

**Comment by Sampad18** [comment]
Creating a new pull request with

**Pull request closed without merging**
