### PR TITLE
Resolve issue 1475 sticky nav-bar

### LINKED ISSUE #1475: Feature: Sticky Nav-bar
### Feature description

You should consider adding a sticky nav bar as it will enhance your user experience because if users want to access a particular section they have to scroll down which leads to bad UX. 
We can do this using CSS3.
I want to work on this issue under GSSOC23, please assign it to me.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Manishak798**
### 👨‍💻 Changes proposed

1. Added CSS to make the Nav bar Sticky. 
2. Fixed a bug that caused content overlapping.
3. Fixed sizes of hero elements.

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
I resolve issue 1475, please let me know If you liked it, and do give your valuable review upon the same.

### 📷 Screenshots
image
image

### CODE REVIEW

**Comment by rohanbabbar04** [comment]
You have merge conflicts do resolve...

**Comment by Manishak798** [comment]
Can you tell me what kind of merge conflicts are?

**Comment by Manishak798** [comment]
Hey @rohanbabbar04  I resolved the conflicts, please check my PR.

**Comment by rohanbabbar04** [comment]
For desktop it looks great, but would also need it to work for different screen sizes.
Look :point_down: 
image

**Comment by Manishak798** [comment]
Okie, I will work on that and submit this to you by tomorrow. But can you tell me should I close this PR then?

**Comment by rohanbabbar04** [comment]
No, you can commit to this branch only let it continue

**Comment by Manishak798** [comment]
hey @rohanbabbar04 , I have applied media queries accordingly please check.
image

**Comment by Manishak798** [comment]
Hey @rohanbabbar04, Please check my PRs, let me known your views about the same.

**Comment by Manishak798** [comment]
@rohanbabbar04 Please check my PR, and let me know what you think about it.

**Comment by Manishak798** [comment]
Hey @rohanbabbar04 please check my PRs.

**Comment by rohanbabbar04** [comment]
Hi @Manishak798, sorry I have been a little busy over the last two days...
I will review it today or tomorrow...

**Comment by Manishak798** [comment]
No worries @rohanbabbar04 take your time.

**Comment by Manishak798** [comment]
Hey @rohanbabbar04 , Kindly check my PR and let me know your views on the same.

**Comment by rohanbabbar04** [comment]
> For desktop it looks great, but would also need it to work for different screen sizes. Look 👇 image

Still this problem is there...

**Comment by Manishak798** [comment]
Kindly tell me in which screen resolutions this is showing up..

**Comment by rohanbabbar04** [comment]
[Check Here](https://deploy-preview-1482--aec-library-wbsite.netlify.app/), haven't tested it locally but this is not showing for any smaller screen sizes

**Comment by Manishak798** [comment]
Hey @rohanbabbar04, according to your concerns I performed retesting of my code and also checked the link you provided me on my mobile phone, It is working seamlessly, I have also inspected the website on different resolutions available on Chrome, and too gave me the accurate result. I am providing you the screenshot below and I highly insist you to please text it out locally or tell me the accurate resolution where you are seeing this error.
image

**Comment by Manishak798** [comment]
Hey @rohanbabbar04 I have made the changes accordingly, found the bug and I resolved it, Please check this out now.
image

**Comment by rohanbabbar04** [comment]
Now, it looks good  :D
Thanks @Manishak798

**Comment by Manishak798** [comment]
You're welcome, @rohanbabbar04.

**Pull request merged**
