### PR TITLE
Created Contributors page

### PR DESCRIPTION
**Pull request by Abdullah-Irfan-web**
@SauravMukherjee44 Created Contributors page with their photos and github profile and added it to the navbar

### CODE REVIEW

**Review by SauravMukherjee44 — APPROVED** [review]

**Comment by SauravMukherjee44** [comment]
@Abdullah-Irfan-web Great, Just add the Github profile of each contributor with a button.

**Comment by Abdullah-Irfan-web** [comment]
@SauravMukherjee44 the github profile is already linked with the name
You want me to make the name of each Contributor as a button?

**Comment by SauravMukherjee44** [comment]
Yes

**Comment by SauravMukherjee44** [comment]
Sent me a mail at : mesouravofficial@gmail.com
Need a discussion

**Pull request merged**
