### PR TITLE
#712 Fixed page footer buttons

### LINKED ISSUE #712: Bug Report: About Page footer not functional.
### Reproduction steps

Link to Donate Books and FAQ button in footer not working.

Steps - 

1. Creating id for FAQ section.
2. Linking respective path directory to its button in footer.

GSSoc -22

### Expected behavior

Should Redirect to this page.

image

### Actual Behavior

Same for FAQ page.

image

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by ABHID10**
### 🛠️ Fixes Issue 

Closes #712 

### 👨‍💻 Changes proposed

- Created id for FAQ section and linked to its respective footer button.
- Linked donate books directory to its respective footer button.

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
image    

image

### CODE REVIEW

**Comment by Anshika-Srivastava** [comment]
Hey! @ABHID10  the FAQ button is taking us to the home-page. Try to redirect it to FAQ section

**Review by Anshika-Srivastava — CHANGES_REQUESTED** [review]
Hey! @ABHID10 the FAQ button is taking us to the home-page. Try to redirect it to FAQ section

**Comment by ABHID10** [comment]
I tried to solve it(FAQ button issue) but was unable to solve.
Please can you help me ??

**Comment by ABHID10** [comment]
Did as you said but still isn't functional .

**Comment by Anshika-Srivastava** [comment]
Okay but resolve the conflicts please

**Comment by Gulnaz44** [comment]
Hello!
Please assign me this issues

**Pull request closed without merging**
