### PR TITLE
Implemented Form Data to Email

### PR DESCRIPTION
**Pull request by yadavashishdhirendra**
Hey @SauravMukherjee44 Implemented this feature I am attaching one video of Testing on loaclhost I have Implemented this using phpmailer so except github it work on any server u can also check the documentation of phpmailer To get emails on your email just change the email in send.php file located in public folder that's it.
[Testing.zip](https://github.com/SauravMukherjee44/Aec-Library-Website/files/7274134/Testing.zip)

### CODE REVIEW

**Comment by SauravMukherjee44** [comment]
Share links and screenshots to view your change.

**Comment by yadavashishdhirendra** [comment]
> Share links and screenshots to view your change.

Plz check the above comment I have attached a zip File Namely (Testing.zip) click on it will download automatically Which contains a video of Testing form Kindly check and let me know if you have any doubt.

**Comment by SauravMukherjee44** [comment]
Great, How could i add my mail, to that?
add this mail: mesouravofficial@gmail.com

**Comment by yadavashishdhirendra** [comment]
> Great, How could i add my mail, to that? add this mail: [codeincommunity@gmail.com](mailto:codeincommunity@gmail.com)

Okay I am adding This email in code I am sending one test mail on your mail check your email for testing!

**Pull request merged**
