### PR TITLE
Added youtube videos and ncert books

### PR DESCRIPTION
**Pull request by Abdullah-Irfan-web**
I have added videos under Youtube videos section and class 12 ncert books in ncert section
Also question bank section is not working properly can i fix it too?

### CODE REVIEW

**Comment by SauravMukherjee44** [comment]
Could you share the screenshot of the changes? And fix the question bank section.

**Comment by Abdullah-Irfan-web** [comment]
@SauravMukherjee44 OK I will fix the question bank section and will share the screenshots

**Review by SauravMukherjee44 — APPROVED** [review]

**Comment by SauravMukherjee44** [comment]
Any updates?

**Comment by Abdullah-Irfan-web** [comment]
Yes i will fix all the issues by tomorrow!
Thanks for waiting

**Comment by Abdullah-Irfan-web** [comment]
hello @SauravMukherjee44 i have added additional resources and fixed the question bank section as well.
Also added study materials PDF.......Some screenshots are attached

Screenshot (34)
Screenshot (35)
Screenshot (36)
Screenshot (37)

**Comment by SauravMukherjee44** [comment]
@Abdullah-Irfan-web Great Work 🙌

**Comment by Abdullah-Irfan-web** [comment]
@SauravMukherjee44 thank you so much 🙋‍♂️

**Pull request merged**
