### PR TITLE
Fixed Bugs in Donate-books

### PR DESCRIPTION
**Pull request by Drish-xD**
Changes made 

- Fixed Navbar , footer
- Fixed form alignments 
- made page responsive for any device

### CODE REVIEW

**Comment by Drish-xD** [comment]
@SauravMukherjee44 Review change and merge as soon as possible :)

**Comment by SauravMukherjee44** [comment]
great work

**Comment by SauravMukherjee44** [comment]
add the icons at the footer and particle.js at the blue background. Do asap! I will merge by today.

**Comment by SauravMukherjee44** [comment]
???

**Comment by Drish-xD** [comment]
> ???

Sorry i slept !!

**Comment by Drish-xD** [comment]
@SauravMukherjee44 Done 👍🏼

**Review by SauravMukherjee44 — APPROVED** [review]

**Pull request merged**
