### PR TITLE
Change font style and background color

### PR DESCRIPTION
**Pull request by AnkitaPal12**

### CODE REVIEW

**Comment by AnkitaPal12** [comment]
Please check the changes

**Comment by SauravMukherjee44** [comment]
It would be great if you can host your forked repository and host it. So
that I can see the changes and merge the code.

**Comment by AnkitaPal12** [comment]
Yeah sure.
here is the link:
https://ankitapal12.github.io/Aec-Library-Website/

**Comment by SauravMukherjee44** [comment]
Hey, Everything is alright. you just need to adjust the bookshelf now. The alignment in which all the books we're adding is looking bad. 
You can reach out to me for any help: https://www.linkedin.com/in/sauravmukherjee44/
 email: mesouravofficial@gmail.com

**Comment by AnkitaPal12** [comment]
Yeah I have fixed the issue you can check it out.
https://ankitapal12.github.io/Aec-Library-Website/

**Comment by SauravMukherjee44** [comment]
Great, I merging your PR. Now work on other issues.
Happy Contributions!

**Comment by SauravMukherjee44** [comment]
Do follow on GitHub : https://github.com/SauravMukherjee44

**Pull request merged**
