### PR TITLE
I have added a book review section

### LINKED ISSUE #782: we can have a book review section . Feature:
### Feature description

In the ace -library section we can add a book review section so that it can motivate lot of people to read book after the review

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Anisharai10**
In ace library website i have added a book review section . whose code i am uploading separately.

### ✔️ Check List (Check all the applicable boxes) 

- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Anisharai10** [comment]
i have added a book review section issue #782 has been resolved

**Review by devaaquib — CHANGES_REQUESTED** [review]
@Anisharai10  The image link is broken.

**Comment by Anisharai10** [comment]
> @Anisharai10 The image link is broken.
can you please elaborate a bit i am unable to understand

**Comment by Anisharai10** [comment]
Can you elaborate a bit i am unable to understand.

**Comment by Anisharai10** [comment]
I have added the full link of image please check and let me know if it's
fine or not.

**Comment by Anisharai10** [comment]
Can you please check and let me know if anything else is required.
Otherwise please close the issue.

**Comment by Anisharai10** [comment]
@devaaquib I have resolved the issue please check and let me know if it's fine or not .

**Comment by SauravMukherjee44** [comment]
@Anisharai10 Add this page's link in the home page too, So that anyone can access it.

**Comment by Anisharai10** [comment]
@SauravMukherjee44  i have commited the issue and added the review section to home page. Please check and let me know if it's fine or not.

**Review by SauravMukherjee44 — APPROVED** [review]

**Pull request merged**
