### PR TITLE
show password feature working

### PR DESCRIPTION
**Pull request by codersmiti**
### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by codersmiti** [comment]
now the show password feature is working.Please look into it and merge my pull request

**Review by SauravMukherjee44 — APPROVED** [review]

**Comment by codersmiti** [comment]
if you feel this commits okay then please merge this pull request

**Review by devaaquib — CHANGES_REQUESTED** [review]
@codersmiti Please remove the value form password by default it shows aeclibrary. Some users take it wrong.

**Comment by codersmiti** [comment]
Ohk I will change it

**Comment by codersmiti** [comment]
I have made the changes @devaaquib

**Review by devaaquib — APPROVED** [review]

**Comment by codersmiti** [comment]
Thank you.It was fun solving this issue @SauravMukherjee44 @devaaquib

**Pull request merged**
