### PR TITLE
Changed home page ui as suggested in issue #195

### PR DESCRIPTION
**Pull request by HetviSoni**
Links to other pages(donate books, contact us)  accessible properly
Screenshot (1266)

### CODE REVIEW

**Comment by SauravMukherjee44** [comment]
Implement the whole Ui at Once. Add other sections like add book and table on the home screen also.

**Comment by HetviSoni** [comment]
Yes sure. Will do it

**Comment by SauravMukherjee44** [comment]
image

**Comment by SauravMukherjee44** [comment]
host your repo and share the link below

**Comment by HetviSoni** [comment]
https://hetvisoni.github.io/Web-clone/

**Comment by SauravMukherjee44** [comment]
Great Work

**Comment by SauravMukherjee44** [comment]
update your repo and fix some bugs

**Comment by SauravMukherjee44** [comment]
Add book option and table in the home screen

**Comment by HetviSoni** [comment]
Yes sure. It would be much helpful if you merge this so that other people also could continue with this.

**Comment by SauravMukherjee44** [comment]
No, Add the book issue and table then only I can merge. after that you can fix other bugs.

**Comment by HetviSoni** [comment]
@SauravMukherjee44 I have added it. Please check it.

**Comment by SauravMukherjee44** [comment]
image

**Comment by SauravMukherjee44** [comment]
Place the table in the blank space.(Right Side)

**Comment by SauravMukherjee44** [comment]
When open the website it opens from the mid, try to fix it so that it opens from nav section.

**Comment by HetviSoni** [comment]
Hey check this out. Is it okay now?

**Comment by SauravMukherjee44** [comment]
Perfect! Add book button is not working. Look into the js file. And do fetch upstream update your current repo.

**Comment by SauravMukherjee44** [comment]
Do it by today, I will merge today.

**Comment by HetviSoni** [comment]
> Perfect! Add book button is not working. Look into the js file. And do fetch upstream update your current repo.

Actually I am beginner in web dev have just started learning js. So I exactly don't know how to do that.

**Review by SauravMukherjee44 — APPROVED** [review]

**Pull request merged**
