### PR TITLE
Convert imges into Webp format

### PR DESCRIPTION
**Pull request by parasss19**
### 🛠️ Fixes Issue

#1393

### 👨‍💻 Changes proposed
-  Aec-Library-Website is fully based on its images and images play important role in it
- I have converted each and every images in so many different files (around 700+ img took me around 2 days) into webp format
- I review everything and no image is broken every image is properly loaded in whole website

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
- @SauravMukherjee44 @rohanbabbar04  I converted all the images in png and jpg  format to webp format 
- Some of the images are still in png/jpg format because they are not compatible with webp format
- Please review it

### CODE REVIEW

**Comment by rohanbabbar04** [comment]
image
In the above image, image is not displayed, it is working in the original [Website](https://aec-library-wbsite.netlify.app/resource.html), do correct it

**Comment by parasss19** [comment]
Hey @rohanbabbar04 Now the logo images are visible please review it once 

https://github.com/SauravMukherjee44/Aec-Library-Website/assets/101205226/918960b4-3649-4140-a884-af1dfdbee9f1

**Comment by rohanbabbar04** [comment]
You have merge conflicts do resolve...

**Comment by parasss19** [comment]
> You have merge conflicts do resolve...

hey @rohanbabbar04 I resolved the conflict pls review it now

**Review by rohanbabbar04 — APPROVED** [review]

**Comment by rohanbabbar04** [comment]
Thanks! 
As an extension , can you also replace the images which are broken, I think they don't look appealing and since you are already working on it would be better
image
To solve this either add new images or fix the old images, I'll leave that to you @parasss19

**Comment by parasss19** [comment]
> Thanks! As an extension , can you also replace the images which are broken, I think they don't look appealing and since you are already working on it would be better image To solve this either add new images or fix the old images, I'll leave that to you @parasss19

Hey @rohanbabbar04 I fixed all the images in resources page now all img are visible and i also removed the non working links of some youtube videos and image path and add the correct path 
Please review it

**Comment by rohanbabbar04** [comment]
Thanks! 
Looks good to me

**Pull request merged**
