### PR TITLE
Added Landing Page 

### PR DESCRIPTION
**Pull request by Drish-xD**
This PR is regarding the issue #116. I have done the following changes 
- Added a About section 
- Added a image related to website 
- Landing Page is also responsive 

I am also gonna work on #151 #150 #160 #82 #67

### CODE REVIEW

**Comment by SauravMukherjee44** [comment]
Resolve Conflicts and host the repository on github pages and share the link.

**Comment by Drish-xD** [comment]
> Resolve Conflicts and host the repository on github pages and share the link.

ok 👌🏼

**Comment by Drish-xD** [comment]
All conflicts are resolved and check out the link https://drish-xd.is-a.dev/Aec-Library-Website/

**Comment by SauravMukherjee44** [comment]
Add particle.js in the previous ui only and change the Navbar and Footer. Don't change the Background.

**Comment by Drish-xD** [comment]
> Add particle.js in the previous ui only and change the Navbar and Footer. Don't change the Background.

Done 👍🏼

**Comment by SauravMukherjee44** [comment]
Resolve Conflicts, and remove bubbles.

**Comment by Drish-xD** [comment]
pls merge :)

**Comment by Drish-xD** [comment]
Resolved for now but as everyone is changing the code, conflicts are occurring again and again as the owner of the repo you'll have to fix the conflicts and then merge as it is impossible for me to fix them again and again

**Comment by SauravMukherjee44** [comment]
You can work on other issues, this one has some bugs.

**Comment by Drish-xD** [comment]
> You can work on other issues, this one has some bugs.

Shall I add particle.js in new ui and make a new PR for hacktoberfest :)

**Pull request closed without merging**
