### PR TITLE
Added a typing effect on About us and Resources page #1446

### PR DESCRIPTION
**Pull request by Arjundotadex**
### 🛠️ Fixes Issue
Added a typing effect on the About Us and Resources page

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers
I have used js for the effect.

### 📷 Screenshots
image
image

### CODE REVIEW

**Comment by rohanbabbar04** [comment]
Remove `.vscode/settings.json`
Also if I remember correctly there was a PR you made(I think you closed it), better to mention it over here, so that we could see if all the changes are covered...

**Comment by Arjundotadex** [comment]
Yeah, I closed that PR. I have deleted the file. Pls do check

**Comment by rohanbabbar04** [comment]
Mention that PR over here..

**Comment by rohanbabbar04** [comment]
#1302  - The PR you closed...

@Arjundotadex  I don't really think adding effect to `About Us` and `Courses` makes sense. I think we should revert it back and instead add effect on the sub topics inside Courses like Web dev courses, App development courses, etc...

**Comment by Arjundotadex** [comment]
@rohanbabbar04 Alright got it!!

**Pull request closed without merging**
