### PR TITLE
Make the website responsive for mobile phone 🐱‍🏍 #35 /issue35

### PR DESCRIPTION
**Pull request by rahulaarora**
made home page responsive to mobiles (414px)
testing device: iPhone 6/7/8 Plus 
also fixed some js error in script.js

### CODE REVIEW

**Comment by rahulaarora** [comment]
@SauravMukherjee44 
plz review

**Comment by SauravMukherjee44** [comment]
Hey, Could you just host your site on GitHub Pages and share the link below.

**Comment by SauravMukherjee44** [comment]
Resolved Conflicts!

**Comment by rahulaarora** [comment]
yeah sure

**Comment by rahulaarora** [comment]
resolved all conflicts 
check now @SauravMukherjee44

**Comment by rahulaarora** [comment]
https://github.com/rahulaarora/Aec-Library-Website/tree/rahulaarora/issue35 
here is the branch link @SauravMukherjee44 
fork it or download the code and 
run it live server to preview changes
looking something like this-->
Web capture_2-10-2021_222724_localhost

**Comment by SauravMukherjee44** [comment]
Great, Just resolve the conflicts again !

**Comment by rahulaarora** [comment]
sure

**Comment by rahulaarora** [comment]
done @SauravMukherjee44 
merge now
conflicts solved

**Pull request merged**
