### PR TITLE
Improving recommended section UI,issue #639

### PR DESCRIPTION
**Pull request by erdivyanshu**
### ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

I changed the UI of book counter and Recommended book section.
please,tell if you want any further changes.

### 📷 Screenshots
SS:1:

Screenshot from 2022-03-15 02-08-28

SS:2:

Screenshot from 2022-03-15 02-11-30

### CODE REVIEW

**Comment by SauravMukherjee44** [comment]
@erdivyanshu Loading time of your deployment version is too high. Also, improve the UI of your build.

**Comment by devaaquib** [comment]
@erdivyanshu Please resolved the conflict.

**Comment by erdivyanshu** [comment]
@SauravMukherjee44 I'm working on it.

**Comment by erdivyanshu** [comment]
@devaaquib Yes,I will make changes as suggested by @SauravMukherjee44.

**Pull request closed without merging**
