### PR TITLE
Html5 layout error

### PR DESCRIPTION
**Pull request by NarendraKoya999**
### 🛠️ Fixes Issue
**I have modified HTML5 Layout Errors**
**BEFORE Modification:**
`<nav</nav>` , 3 `<div></div>` sections in the` <body></body>` section in **contributors.html**
**Live Code :**
```
<body>
   <nav></nav>
   <div></div>
  <div></div>
  <div><footer></footer></div>
</body>
```
**AFTER Modification:**
`<header></header>`,`<nav></nav>`,`<main></main>`, 2` <section></section>` tags added in **contribution.html**
```
<body>
  <header>
       <nav></nav>
  </header>
  <main>
     <section>
         <div></div>
    </section>
    <section>
         <div></div>
    </section>
  </main>
  <footer></footer>  // Remove <div></div>tag around the <footer></footer> section.
</body>
````
_**NOTE: Already much content provided in Each Tag and Separate Sections .That's Why I have not added any code inside Tags **_

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @SauravMukherjee44 . At the Starting of the GSSOC'23 Program, I made a Small Mistake like Directly I made a PR Before Raising Issue. Because of I am New to Open Source Program .Kindly  Review and Merge this Time with add Specific Labels.

**Review by rohanbabbar04 — CHANGES_REQUESTED** [review]
image
Look like in the about page multiple social icons and `Quick Links` is visible, do correct it

**Comment by rohanbabbar04** [comment]
i see you have not done any changes and requested a review @NarendraKoya999, is there some issue?

**Comment by NarendraKoya999** [comment]
> i see you have not done any changes and requested a review @NarendraKoya999, is there some issue?

- I am correct my PR related Issue in Codebase. You are raised Quick Link Section and Social Icons Visibility in about Page has two Times.
- After Check with my Updated Changes, Does not Shown these above Errors.

**Comment by rohanbabbar04** [comment]
I think you have not pushed your code as I cannot see your commits

**Comment by NarendraKoya999** [comment]
I will check one more time and update it as soon as possible @rohanbabbar04

**Comment by NarendraKoya999** [comment]
> I think you have not pushed your code as I cannot see your commits Do check and let me know @NarendraKoya999 I assume it has to be once 👇 image

I have Below Issue When Pushing My Changes. How to resolve?
aeclibrary-3

**Comment by NarendraKoya999** [comment]
> I think you have not pushed your code as I cannot see your commits Do check and let me know @NarendraKoya999 I assume it has to be once 👇 image

**Hi @rohanbabbar04 . Actually, style.css File  has One Conflict As Before shown in My VS Code. That's Why I did not push My Update changes not allowing into  your repository. Please Rectify that Conflict in style.css. After that, My Code push changes Appear**

**Comment by rohanbabbar04** [comment]
i Don't see any conflicts @NarendraKoya999 ?

**Comment by rohanbabbar04** [comment]
@NarendraKoya999 any updates?

**Comment by NarendraKoya999** [comment]
> @NarendraKoya999 any updates?

Hi @rohanbabbar04 . Next One Hour I will Update the changes related to this PR. I have faced Local repository Problems.

**Comment by rohanbabbar04** [comment]
> > @NarendraKoya999 any updates?
> 
> Hi @rohanbabbar04 . Next One Hour I will Update the changes related to this PR. I have faced Local repository Problems.

No issues you can take your time, If you want any help you can comment here...

**Comment by NarendraKoya999** [comment]
> > > @NarendraKoya999 any updates?
> > 
> > 
> > Hi @rohanbabbar04 . Next One Hour I will Update the changes related to this PR. I have faced Local repository Problems.
> 
> No issues you can take your time, If you want any help you can comment here...
> I have this Below Merge Conflicts Errors . Please Help Me . How to Resolve Issue. My PR Only Focusing HTML File. Why this Happens?

aeclibrary-4

**Comment by rohanbabbar04** [comment]
Yeah as you wish...

**Comment by NarendraKoya999** [comment]
> Yeah as you wish...

Hi @rohanbabbar04 . I have raised New PR related to this Referenced Basis PR No #1431 . Please Check?

**Pull request closed without merging**
