### PR TITLE
button style added with icon

### PR DESCRIPTION
**Pull request by garg-kunal**
A new style added for with search icon on button

### CODE REVIEW

**Comment by SauravMukherjee44** [comment]
Could you share screenshots or links to view the changes.

**Comment by garg-kunal** [comment]
> Could you share screenshots or links to view the changes.

image

**Comment by SauravMukherjee44** [comment]
There are some issues, do resolve them
image
.

**Comment by garg-kunal** [comment]
Sorry I didn't get any issue I attached 2 pics for your reference.


[image: image.png]
[image: image.png]

**Pull request merged**
