### PR TITLE
margin correction

### PR DESCRIPTION
**Pull request by samyberkane04**
### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
Capture d’écran de 2022-03-28 09-25-05

### CODE REVIEW

**Comment by samyberkane04** [comment]
@SauravMukherjee44 

hello, can you merge this pull requests please ?

**Comment by Anshika-Srivastava** [comment]
Please attach the screenshots of the changes you have made.

**Comment by samyberkane04** [comment]
@Anshika-Srivastava 
the screenshot of the changes :
Capture d’écran de 2022-03-28 09-25-05

**Review by mwildrick4389 — APPROVED** [review]

**Comment by Anshika-Srivastava** [comment]
@samyberkane04 the screenshots are not visible

**Comment by samyberkane04** [comment]
@Anshika-Srivastava
Capture d’écran de 2022-03-28 09-25-05

**Comment by samyberkane04** [comment]
@Anshika-Srivastava 

hello, can you merge this pull requests please ?

**Comment by samyberkane04** [comment]
@Anshika-Srivastava

hello, can you merge this pull requests please ?

**Pull request closed without merging**
