### PR TITLE
Added the header and footer in Donate book page

### PR DESCRIPTION
**Pull request by sangeeta874**
https://sangeeta874.github.io/Aec-Library-Website/

### CODE REVIEW

**Comment by SauravMukherjee44** [comment]
Resolve Conflicts !

**Comment by sangeeta874** [comment]
resolved

**Comment by SauravMukherjee44** [comment]
Sorry Once Again !

**Review by SauravMukherjee44 — APPROVED** [review]

**Comment by sangeeta874** [comment]
Resolved the conflict !!

**Comment by SauravMukherjee44** [comment]
Great!

For any help you can reach out here : https://sauravmukherjee.bio.link/

**Comment by SauravMukherjee44** [comment]
There are some issues submit button is not visible and form is not at the center. Fix Asap!

**Comment by SauravMukherjee44** [comment]
@sangeeta874 Okay ???

**Comment by sangeeta874** [comment]
okkayyy

**Pull request merged**
