### PR TITLE
fix: Added and Modified aria-label, target, title, rel attributes and It's Data in 6 Files

### PR DESCRIPTION
**Pull request by NarendraKoya999**
### 👨‍💻 Changes proposed

- In about.html File, Added aria-label, title, rel attributes and Edited title attribute text related to GitHub
- In blogs.html, Added aria-label, rel, and Modified title attribute text in all Social Links
- In contributors.html File, Added target, title, rel, aria-label attributes and Edited title attribute text related to GitHub
- In index.html File, Modified aria-label and title attribute Texts related to All Social Icons
- In donate-books.html File, Added title, rel, target, aria-label attributes and Modified target attribute text related to GitHub Social Icon.
- In resource.html File, Added rel, aria-label, title attributes.

### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### 📄 Note to reviewers

- Above my Changes are links to My Issue Description. Additionally , I added Modifications in blogs.html and about.html File. Because of, I believing Consistency and Clean Code matters for Building Website. So, I can moved those Files.

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @rohanbabbar04 . Please review on this PR

**Review by rohanbabbar04 — COMMENTED** [review]
Remove `(External Link)` from each title.

**Comment by rohanbabbar04** [comment]
Looks good thanks !

**Review by rohanbabbar04 — APPROVED** [review]

**Comment by NarendraKoya999** [comment]
> Looks good thanks !

I did almost 6 Files changed related to above Issues. If any chances to add level 2. Because of, In other repositories considered these type of Files Changes almost 6 Files to added Level 2 Label. Kindly Consider my Request @rohanbabbar04

**Comment by NarendraKoya999** [comment]
Kindly Taken  My above Request @rohanbabbar04

**Comment by NarendraKoya999** [comment]
> Kindly Taken My above Request @rohanbabbar04

Any Update on My Quote @rohanbabbar04

**Pull request merged**
