### PR TITLE
changes made #769

### PR DESCRIPTION
**Pull request by vaishnavi2810-code**
### ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Anshika-Srivastava — CHANGES_REQUESTED** [review]
Even after alerting, the form is allowing you to proceed with address after you press OK. Please fix that.

**Review by devaaquib — APPROVED** [review]

**Comment by vaishnavi2810-code** [comment]
Resolved the issue #770 of submisson happening even after alert. The updated code sends an alert on clicking submit button also.

**Comment by vaishnavi2810-code** [comment]
Please merge the updated code

**Review by SauravMukherjee44 — APPROVED** [review]

**Comment by vaishnavi2810-code** [comment]
Sir please assign the labels to this or #770

**Comment by vaishnavi2810-code** [comment]
Working on it now

**Pull request merged**
