### PR TITLE
updated footer in all pages

### PR DESCRIPTION
**Pull request by the-centinal**
solved the issue

### CODE REVIEW

**Review by Anshika-Srivastava — APPROVED** [review]

**Review by devaaquib — CHANGES_REQUESTED** [review]
Solved the issue

**Comment by the-centinal** [comment]
solved the conflicts sir

**Comment by devaaquib** [comment]
@the-centinal  The UI is broken please have a look at it and check your code again.

Screenshot (128)
Screenshot (129)

**Comment by the-centinal** [comment]
yes sir

**Comment by the-centinal** [comment]
sir how do i revert these changes???? or should i make a new branch for this issue as i cant find the mistake which has resulted to this problem ??

**Comment by the-centinal** [comment]
sir please can you help?? i cant find a way to revert these changes

**Comment by devaaquib** [comment]
@the-centinal  msg me on LinkedIn. You can find the link in my GitHub profile.

**Comment by the-centinal** [comment]
sir please accept me as connection

**Comment by devaaquib** [comment]
@the-centinal  i can't see your connection request. send me your URL here.

**Comment by the-centinal** [comment]
https://www.linkedin.com/in/praveen-yadav-3a250b208/

**Comment by the-centinal** [comment]
sir please accept  my request or reply here i'm stuck here

**Comment by the-centinal** [comment]
can i solve  this in new branch??

**Pull request closed without merging**
