### PR TITLE
fixes issue #85 - forms do not submit when empty

### PR DESCRIPTION
**Pull request by akkaraju-satvik**
forms now do not submit when any of the input fields are empty.

added `required` attribute to input fields

### CODE REVIEW

**Comment by SauravMukherjee44** [comment]
Can you host your GitHub repo on GitHub pages and share the link below. So that I can merge your pr.

**Comment by akkaraju-satvik** [comment]
https://akkaraju-satvik.github.io/Aec-Library-Website/

**Comment by SauravMukherjee44** [comment]
Do correction in JS file. Add book button is not working

**Comment by akkaraju-satvik** [comment]
> Do correction in JS file. Add book button is not working

what exactly do i have to do to reproduce this bug?

**Comment by yadavashishdhirendra** [comment]
Hey @SauravMukherjee44 I would like to work on Book Donation Form for Sending form data to a email. Can u assign it to me.

**Comment by SauravMukherjee44** [comment]
@yadavashishdhirendra Create a issue for the same !

**Comment by akkaraju-satvik** [comment]
hey @SauravMukherjee44 may i know the reason for this PR not being merged?

**Pull request closed without merging**
