### PR TITLE
added recommended book section

### PR DESCRIPTION
**Pull request by rajmunkhan**
@SauravMukherjee44  I have added recommended book section in index.html page, plz check that out and let me know if you need any changes.

### CODE REVIEW

**Comment by SauravMukherjee44** [comment]
Host your site on github pages and share the link below or share screenshot

**Comment by rajmunkhan** [comment]
> Host your site on github pages and share the link below or share screenshot



this is the recommended section of the books

**Comment by rajmunkhan** [comment]
@SauravMukherjee44 any suggestion?

**Comment by rajmunkhan** [comment]
@SauravMukherjee44 can u plz say if it is ok or not?

**Comment by SauravMukherjee44** [comment]
Change the location of Recommended Books.
Place here:  
image

**Comment by SauravMukherjee44** [comment]
Add 3-4 Books and link them with the resource page.

**Comment by rajmunkhan** [comment]
@SauravMukherjee44 I have updated the recommended section and the page is still responsive

**Pull request closed without merging**
