### PR TITLE
Resource page Header UI change and Minor bug fix in Home page

### PR DESCRIPTION
**Pull request by ngsanthosh**
### 🛠️ Fixed

- Home page being redirected from Home page itself
- Styled the taskbar of Resource page better.

### 📷 Screenshots
Before:
image

After:
image

### CODE REVIEW

**Comment by ngsanthosh** [comment]
@SauravMukherjee44 Could you please review my PR?

**Comment by ngsanthosh** [comment]
@SauravMukherjee44 Please do the needfulness

**Review by IAmTamal — CHANGES_REQUESTED** [review]
image


Fix this please

and also the search box which says `seach for names`

**Comment by ngsanthosh** [comment]
> image
> 
> Fix this please
> 
> and also the search box which says `seach for names`

image

Actually, I have made the changes in the resource.css file also, It should have been reflected. Maybe shall I change that placeholder("Search for name..?")

**Comment by IAmTamal** [comment]
@ngsanthosh You need to make it so that the search box is not that big vertically
Also mention your issue number in the PR

**Comment by ngsanthosh** [comment]
@IAmTamal I have done the necessary changes. Please review :)

**Review by IAmTamal — APPROVED** [review]
LGTM, will be merged soon ✅

**Comment by ngsanthosh** [comment]
@IAmTamal @SauravMukherjee44 I would be so glad if you could add "hacktoberfest-accepted" label for this merged PR.

**Pull request merged**
