### PR TITLE
Fixed minor styling bugs and rectified 'back' redirection issue in SignUp page

### PR DESCRIPTION
**Pull request by ngsanthosh**
### 🛠️ Fixes Issue

-  Changed styling issues in signup page
-  The Redirection path for home page is now correctly navigated

### 📷 Screenshots

Before: 
image
After:
image

### CODE REVIEW

**Comment by ngsanthosh** [comment]
Hi @SauravMukherjee44, Could you please review my PR? ;)

**Comment by SauravMukherjee44** [comment]
Resolve conflicts.

**Comment by ngsanthosh** [comment]
Conflicts are resolved and the whole "relative path" is given for redirection to the home page from the sign up page

**Comment by ngsanthosh** [comment]
@SauravMukherjee44 I would be glad if you could review and do the needfulness

**Pull request closed without merging**
