### PR TITLE
Validation added on Book Donation Form issue#1207 resolved

### PR DESCRIPTION
**Pull request by Geeta259**
## Fix issue
Issue #1207 

## Changes
Validations added on book donation form
1)Empty field validation on input fields and dropdown menus
2)Email validation 
3)contact no should be 10 digits

Screenshot (310)
Screenshot (308)
Screenshot (309)

@SauravMukherjee44 Check it issue #1207 resolved!

### CODE REVIEW

**Comment by Geeta259** [comment]
@SauravMukherjee44  @rohanbabbar04 Please review this PR linked with issue #1207.

**Comment by rohanbabbar04** [comment]
Overall Great Work :)
Some changes I would like to point out

**Comment by rohanbabbar04** [comment]
image
In the image you can see `Email` and `Contact Number` are overlapped. Do modify it

**Comment by rohanbabbar04** [comment]
Also currently the optional field `Landmark` and `Alternate Phone` also require input to proceed, do correct it

**Comment by Geeta259** [comment]
@rohanbabbar04 I again make PR #1407 after did required changes.
Hopes Now it's work!!

**Pull request closed without merging**
